[package]
name = "test_sst_importer"
version = "0.1.0"
edition = "2018"
publish = false
description = "test helpers for sst_importer"

[lib]
test = false

[features]
protobuf-codec = [
  "engine_lmdb/protobuf-codec",
  "tuplespaceInstanton/protobuf-codec",
  "ekvproto/protobuf-codec",
]
prost-codec = [
  "engine_lmdb/prost-codec",
  "tuplespaceInstanton/prost-codec",
  "ekvproto/prost-codec",
]

[dependencies]
crc32fast = "1.2"
engine_lmdb = { path = "../engine_lmdb" }
edb = { path = "../edb" }
tuplespaceInstanton = { path = "../tuplespaceInstanton" }
ekvproto = { git = "https://github.com/whtcorpsinc/ekvproto.git", default-features = false }
uuid = { version = "0.8.1", features = ["serde", "v4"] }
