[package]
name = "causetq_allegrosql"
version = "0.0.1"
workspace = ".."

[lib]
name = "causetq_allegrosql"
path = "lib.rs"

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"



[dependencies.edbn]
path = "..edb/edbn"

[dependencies.causetq_allegrosql]
path = "../allegro"

[dependencies.edb_sql]
path = "../allegrosql"

[dependencies.allegrosql_promises]
path = "../allegrosql-promises"

[dependencies.edb_causetq_parityfilter]
path = "../causetq-parityfilter"

