[package]
name = "external_causet_storage"
version = "0.0.1"
edition = "2018"
publish = false

[features]
protobuf-codec = ["ekvproto/protobuf-codec"]
prost-codec = ["ekvproto/prost-codec"]

[dependencies]
bytes = "0.5.3"
futures = "0.3"
futures-executor = "0.3"
futures-io = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["io"] }
http = "0.2.0"
ekvproto = { git = "https://github.com/whtcorpsinc/ekvproto.git", default-features = false }
hyper = "0.13.3"
hyper-tls = "0.4.1"
rand = "0.7"
rusoto_core = "0.44.0"
rusoto_s3 = "0.44.0"
rusoto_util = { path = "../rusoto_util" }
serde_json = "1.0"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
# better to not use slog-global, but pass in the logger
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
tame-gcs = { version = "0.7.0", features = ["async-multipart"] }
tame-oauth = "0.4.2"
edb_alloc = { path = "../edb_alloc" }
tokio = { version = "0.2.13", features = ["time"] }
url = "2.0"

[dev-dependencies]
structopt = "0.3"
rusoto_mock = "0.44.0"
tempfile = "3.1"
rust-ini = "0.14.0"
