[package]
name = "error_code"
version = "0.0.1"
edition = "2018"
publish = false

[features]
prost-codec = [
  "ekvproto/prost-codec",
  "grpcio/prost-codec",
]
protobuf-codec = [
  "ekvproto/protobuf-codec",
  "grpcio/protobuf-codec",
]

[lib]
name = "error_code"
path = "src/lib.rs"

[[bin]]
name = "error_code_gen"
path = "bin.rs"

[dependencies]
lazy_static = "1.3"
violetabft = { version = "0.6.0-alpha", default-features = false }
ekvproto = { git = "https://github.com/whtcorpsinc/ekvproto.git", default-features = false }
edb_alloc = { path = "../edb_alloc" }
grpcio = { version = "0.6", default-features = false, features = ["openssl-vlightlikeored"] }
toml = "0.4"
serde = { version = "1.0", features = ["derive"] }
