[package]
name = "test_util"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
encryption = { path = "../encryption" }
fail = "0.3"
grpcio = { version = "0.6", default-features = false, features = ["openssl-vlightlikeored"] }
ekvproto = { git = "https://github.com/whtcorpsinc/ekvproto.git", default-features = false }
rand = "0.7"
rand_isaac = "0.2"
security = { path = "../security" }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
tempfile = "3.0"
violetabftstore::interlock:: = { path = "../violetabftstore::interlock::" }
time = "0.1"
