[package]
name = "edbn_promises"
version = "0.0.1"
workspace = ".."

[lib]
name = "edbn_promises"
path = "lib.rs"

[features]
sqlcipher = ["rusqlite/sqlcipher"]

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"

[dependencies.edbn]
path = "../edb/edbn"

[dependencies.allegrosql_promises]
path = "../allegro-promises"

[dependencies.rusqlite]
version = "0.24.2"
features = ["limits"]
