[package]
name = "milevadb_query_datatype"
version = "0.0.1"
edition = "2018"
publish = false
description = "Data type of a query engine to run MilevaDB pushed down executors"

[features]
protobuf-codec = [
  "ekvproto/protobuf-codec",
  "fidel_timeshare/protobuf-codec",
]
prost-codec = [
  "ekvproto/prost-codec",
  "fidel_timeshare/prost-codec",
]

[dependencies]
bitfield = "0.13.2"
bitflags = "1.0.1"
boolinator = "2.4.0"
chrono = "0.4"
chrono-tz = "0.5.1"
codec = { path = "../codec" }
error_code = { path = "../error_code" }
failure = "0.1"
hex = "0.3"
ekvproto = { git = "https://github.com/whtcorpsinc/ekvproto.git", default-features = false }
lazy_static = "1.3"
match_template = { path = "../match_template" }
nom = { version = "5.1.0", default-features = false, features = ["std"] }
num = { version = "0.2", default-features = false }
num-promises = "0.2"
num-derive = "0.3"
ordered-float = "1.0"
protobuf = "2"
quick-error = "1.2.3"
regex = "1.1"
serde = "1.0"
serde_json = "1.0"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
violetabftstore::interlock:: = { path = "../violetabftstore::interlock::" }
fidel_timeshare = { git = "https://github.com/whtcorpsinc/fidel_timeshare.git", default-features = false }
static_assertions = { version = "1.0", features = ["nightly"] }
milevadb_query_common = { path = "../milevadb_query_common" }
edb_alloc = { path = "../edb_alloc" }
