[package]
name = "edb"
version = "0.0.1"
edition = "2018"
publish = false

[features]
protobuf-codec = [
  "violetabft/protobuf-codec",
  "ekvproto/protobuf-codec",
]
prost-codec = [
  "violetabft/prost-codec",
  "ekvproto/prost-codec",
]

[dependencies]
error_code = { path = "../error_code" }
hex = "0.4"
protobuf = "2"
quick-error = "1.2.3"
edb_alloc = { path = "../edb_alloc" }
violetabftstore::interlock:: = { path = "../violetabftstore::interlock::" }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
ekvproto = { git = "https://github.com/whtcorpsinc/ekvproto.git", default-features = false }
violetabft = { version = "0.6.0-alpha", default-features = false }