[package]
name = "homotopy"
version = "0.0.1"
edition = "2018"
publish = false

[features]                                                          
protobuf-codec = ["eTxnproto/protobuf-codec", "violetabft/protobuf-codec"]
prost-codec = ["eTxnproto/prost-codec", "violetabft/prost-codec"]

[dependencies]
allegrosql_promises = { path = "../allegrosql_promises" }
eTxnproto = { git = "https://github.com/whtcorpsinc/eTxnproto.git", default-features = false }
violetabft = { version = "0.0.1-alpha", default-features = false }
