[package]
name = "engine_panic"
version = "0.0.1"
description = "An example EinsteinDB causet_storage engine that does nothing but panic"
edition = "2018"
publish = false

[dependencies]
edb = { path = "../edb" }
edb_alloc = { path = "../edb_alloc" }
# FIXME: Remove this dep from the edb interface
violetabftstore::interlock:: = { path = "../violetabftstore::interlock::" }
