[package]
name = "fidel_client"
version = "0.1.0"
edition = "2018"
publish = false

[features]
protobuf-codec = [
  "grpcio/protobuf-codec",
  "ekvproto/protobuf-codec",
  "txn_types/protobuf-codec",
]
prost-codec = [
  "grpcio/prost-codec",
  "ekvproto/prost-codec",
  "txn_types/prost-codec",
]
failpoints = ["fail/failpoints"]

[dependencies]
error_code = { path = "../error_code" }
futures = "0.3"
grpcio = { version = "0.6", default-features = false, features = ["openssl-vlightlikeored"] }
hex = "0.4"
ekvproto = { git = "https://github.com/whtcorpsinc/ekvproto.git", default-features = false }
lazy_static = "1.3"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
prometheus = { version = "0.8", features = ["nightly", "push"] }
quick-error = "1.2.3"
security = { path = "../security" }
serde = "1.0"
serde_derive = "1.0"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
edb_alloc = { path = "../edb_alloc" }
violetabftstore::interlock:: = { path = "../violetabftstore::interlock::" }
tokio-timer = "0.2"
txn_types = { path = "../txn_types" }
semver = "0.10"
fail = "0.3"
