[package]
name = "edb-server"
version = "0.1.0"
edition = "2018"
publish = false

[features]
failpoints = ["fail/failpoints"]
protobuf-codec = ["ekvproto/protobuf-codec"]
prost-codec = ["ekvproto/prost-codec"]

[lib]
adler32 = "1.0"
async-trait = "0.1.51"
async-speed-limit = "0.3"
backtrace = "0.3.9"
byteorder = "1.2"
codec = { path = "../codec" }
configuration = { path = "../configuration" }
chrono = "0.4"
crc32fast = "1.2"
crossbeam = "0.8.0"
error_code = { path = "../error_code" }
derive_more = "0.99.11"
fail = "0.4.0"
fs2 = "0.4"
futures = "0.3"
fxhash = "0.2.1"
grpcio = { version = "0.7.1", default-features = false, features = ["openssl-vlightlikeored"] }
hex = "0.4"
lazy_static = "1.3"
libc = "0.2"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_debug"] }
num_cpus = "1"
openssl = "0.10"
prometheus = { version = "0.8", features = ["nightly", "push"] }
quick-error = "2.0.0"
rand = "0.8.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-async = "2.3"
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
slog-json = "2.3"
slog-term = "2.4"
sysinfo = "0.15.9"
edb_alloc = { path = "../edb_alloc" }
time = "0.2.24"
fidel_timeshare = { git = "https://github.com/whtcorpsinc/fidel_timeshare.git", default-features = false }
tokio = { version = "1.0.2", features = ["rt-util"] }
tokio-executor = "0.1"
tokio-timer = "0.2"
url = "2"
ekvproto = { git = "https://github.com/whtcorpsinc/ekvproto.git", default-features = false }
minitrace = { git = "https://github.com/whtcorpsinc-incubator/minitrace-rust.git", branch = "master" }
protobuf = "2"


[target.'causet(target_os = "linux")'.dependencies]
procinfo = { git = "https://github.com/edb/procinfo-rs", rev = "5125fc1a69496b73b26b3c08b6e8afc3c665a56e" }
procausets = "0.7"

[dependencies.yatp]
git = "https://github.com/edb/yatp.git"

[dependencies]
panic_hook = { path = "../panic_hook" }
protobuf = "2"
regex = "1.0"
tempfile = "3.0"
toml = "0.4"
utime = "0.2"
walkdir = "2.3"
yamux = "0.18.0"
yansi = "0.6.0"
tokio-util = "0.3"
tokio-io = "0.1"
tokio-tcp = "0.1"
tokio-uds = "0.1"

[dev-dependencies]
quickcheck = "0.9"


