[package]
name = "milevadb_query_normal_expr"
version = "0.0.1"
edition = "2018"
publish = false
description = "A scalar expression of query engine to run MilevaDB pushed down executors"

[dependencies]
base64 = "0.12"
bstr = "0.2.8"
byteorder = "1.2"

codec = { path = "../codec" }
failure = "0.1"
flate2 = { version = "1.0", default-features = false, features = ["zlib"] }
hex = "0.3"
match_template = { path = "../match_template" }
num = { version = "0.2", default-features = false }
openssl = { version = "0.10" }
protobuf = "2"
regex = "1.1"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
milevadb_query_datatype = { path = "../milevadb_query_datatype" }
milevadb_query_common = { path = "../milevadb_query_common" }
milevadb_query_shared_expr = { path = "../milevadb_query_shared_expr" }
violetabftstore::interlock:: = { path = "../violetabftstore::interlock::" }
fidel_timeshare = { git = "https://github.com/whtcorpsinc/fidel_timeshare.git", default-features = false }
twoway = "0.2.0"
uuid = { version = "0.8.1", features = ["v4"] }

[dev-dependencies]
chrono = "0.4"
