[package]
name = "causet_context"
version = "0.0.1"
edition = "2018"
publish = false

[features]
protobuf-codec = [
  "engine_lmdb/protobuf-codec",
  "grpcio/protobuf-codec",
  "ekvproto/protobuf-codec",
  "fidel_client/protobuf-codec",
  "violetabft/protobuf-codec",
  "violetabftstore/protobuf-codec",
  "edb/protobuf-codec",
  "txn_types/protobuf-codec",
]
prost-codec = [
  "engine_lmdb/prost-codec",
  "grpcio/prost-codec",
  "ekvproto/prost-codec",
  "fidel_client/prost-codec",
  "violetabft/prost-codec",
  "violetabftstore/prost-codec",
  "edb/prost-codec",
  "txn_types/prost-codec",
]
tcmalloc = ["edb/tcmalloc"]
jemalloc = ["edb/jemalloc"]
mimalloc = ["edb/mimalloc"]
porBlock = ["edb/porBlock"]
sse = ["edb/sse"]
mem-profiling = ["edb/mem-profiling"]
failpoints = ["edb/failpoints"]

[dependencies]
bitflags = "1.0"
crossbeam = "0.7"
hex = "0.4"
engine_lmdb = { path = "../engine_lmdb" }
edb = { path = "../edb" }
failure = "0.1"
futures = "0.3"
grpcio = { version = "0.6", default-features = false, features = ["openssl-vlightlikeored"] }
ekvproto = { git = "https://github.com/whtcorpsinc/ekvproto.git", default-features = false }
fidel_client = { path = "../fidel_client" }
violetabft = { version = "0.6.0-alpha", default-features = false }
violetabftstore = { path = "../violetabftstore" }
resolved_ts = { path = "../resolved_ts" }
security = { path = "../security" }
semver = "0.10"
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
edb = { path = "../../", default-features = false }
violetabftstore::interlock:: = { path = "../violetabftstore::interlock::" }
tokio = { version = "0.2", features = ["rt-threaded"]}
txn_types = { path = "../txn_types" }
interlocking_directorate = { path = "../interlocking_directorate" }
fail = "0.3"
lazy_static = "1.3"
prometheus = { version = "0.8", default-features = false, features = ["nightly", "push"] }
protobuf = "2.8"
prost = "0.6"

[dev-dependencies]
edb = { path = "../edb" }
tempfile = "3.0"
test_violetabftstore = { path = "../test_violetabftstore" }
test_util = { path = "../test_util" }
panic_hook = { path = "../panic_hook" }

[[test]]
name = "integrations"
path = "tests/integrations/mod.rs"

# To avoid failpoints interfere with normal tests, we separate them.
[[test]]
name = "failpoints"
path = "tests/failpoints/mod.rs"
required-features = ["failpoints"]
