[package]
name = "test_violetabftstore"
version = "0.0.1"
edition = "2018"
publish = false

[features]
protobuf-codec = [
  "engine_lmdb/protobuf-codec",
  "grpcio/protobuf-codec",
  "tuplespaceInstanton/protobuf-codec",
  "ekvproto/protobuf-codec",
  "fidel_client/protobuf-codec",
  "violetabft/protobuf-codec",
  "violetabftstore/protobuf-codec",
  "edb/protobuf-codec",
]
prost-codec = [
  "engine_lmdb/prost-codec",
  "grpcio/prost-codec",
  "tuplespaceInstanton/prost-codec",
  "ekvproto/prost-codec",
  "fidel_client/prost-codec",
  "violetabft/prost-codec",
  "violetabftstore/prost-codec",
  "edb/prost-codec",
]

[dependencies]
crossbeam = "0.7.2"
edb = { path = "../edb" }
engine_lmdb = { path = "../engine_lmdb" }
futures = "0.3"
grpcio = { version = "0.6", default-features = false, features = ["openssl-vlightlikeored"] }
hex = "0.4"
lazy_static = "1.3"
tuplespaceInstanton = { path = "../tuplespaceInstanton" }
ekvproto = { git = "https://github.com/whtcorpsinc/ekvproto.git", default-features = false }
fidel_client = { path = "../fidel_client" }
violetabft = { version = "0.6.0-alpha", default-features = false }
violetabftstore = { path = "../violetabftstore" }
rand = "0.7"
security = { path = "../security" }
slog = { version = "2.3", features = ["max_level_trace", "release_max_level_debug"] }
# better to not use slog-global, but pass in the logger
slog-global = { version = "0.1", git = "https://github.com/breeswish/slog-global.git", rev = "0e23a5baff302a9d7bccd85f8f31e43339c2f2c1" }
tempfile = "3.0"
test_util = { path = "../test_util" }
edb = { path = "../../", default-features = false }
violetabftstore::interlock:: = { path = "../violetabftstore::interlock::" }
tokio-threadpool = "0.1"
tokio-timer = "0.2"
txn_types = { path = "../txn_types" }
encryption = { path = "../encryption" }
tokio = { version = "0.2", features = ["rt-threaded"]}
interlocking_directorate = { path = "../interlocking_directorate" }
fail = "0.3"
