[package]
name = "security"
version = "0.0.1"
edition = "2018"
publish = false

[dependencies]
encryption = { path = "../encryption" }
grpcio = { version = "0.6", default-features = false, features = ["openssl-vlightlikeored"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
violetabftstore::interlock:: = { path = "../violetabftstore::interlock::" }

[dev-dependencies]
tempfile = "3.0"
